import type { BodyPart, HellLevelMechanic, StressType } from './types';

export const BODY_PART_LABELS: Record<BodyPart, string> = {
  mouth: '嘴门',
  throat: '话根',
  eyes: '假笑眼',
  hands: '抢功手',
  back: '背刺点',
  heart: '黑心',
  belly: '贪坑',
  feet: '卡路脚',
  head: '甩锅脑',
  shadow: '画皮影'
};

export const BODY_PART_ORDER: BodyPart[] = [
  'mouth',
  'throat',
  'eyes',
  'hands',
  'back',
  'heart',
  'belly',
  'feet',
  'head',
  'shadow'
];

export const LEVEL_MECHANICS: Record<string, HellLevelMechanic> = {
  hell_tongue: {
    playName: '扎针转盘',
    toolName: '玄机小针',
    toolIcon: '📌',
    fireLabel: '发射扎针',
    hitVerb: '扎中',
    criticalVerb: '封口暴扎',
    finishMove: '口业封针',
    dockHint: '看准指针压到嘴门或话根时发射，一针把嚼话根子的嘴封住。',
    coreMechanic: '看准嘴门弱点，把嚼话根子的口业钉回去。',
    rotationSpeed: 0.62,
    needleQuota: 6,
    weaknessParts: ['mouth', 'throat'],
    obstacleType: 'none',
    specialRule: '新手层：弱点窗口更宽，优先练扎针节奏。',
    recommendedWeapons: ['pin', 'glove'],
    critMultiplier: 2.1,
    timeLimit: 90
  },
  hell_scissor: {
    playName: '剪线轮盘',
    toolName: '断缘剪',
    toolIcon: '✂️',
    fireLabel: '剪断红线',
    hitVerb: '剪中',
    criticalVerb: '离间暴剪',
    finishMove: '恶缘剪断',
    dockHint: '避开红线陷阱，剪背后挑拨和抢功手，离间局就会散。',
    coreMechanic: '避开离间红线，钉住背后挑拨和抢功手。',
    rotationSpeed: 0.78,
    needleQuota: 8,
    weaknessParts: ['back', 'hands'],
    obstacleType: 'blackLines',
    specialRule: '撞到红线会断连击，连续命中才会剪断恶缘。',
    recommendedWeapons: ['pin', 'glove'],
    critMultiplier: 2.15,
    timeLimit: 90
  },
  hell_iron_tree: {
    playName: '铁树钉刑',
    toolName: '铁树长钉',
    toolIcon: '🧷',
    fireLabel: '钉回背刺',
    hitVerb: '钉中',
    criticalVerb: '背刺反钉',
    finishMove: '暗箭回枝',
    dockHint: '不要撞到旧针，抓住背刺点，把它放的冷箭原路钉回去。',
    coreMechanic: '铁树上有旧针障碍，别撞针，专扎背刺点。',
    rotationSpeed: 0.95,
    needleQuota: 8,
    weaknessParts: ['back'],
    obstacleType: 'presetNeedles',
    specialRule: '重复扎同一部位会撞针，节奏要稳。',
    recommendedWeapons: ['pin', 'hammer'],
    critMultiplier: 2.35,
    timeLimit: 85
  },
  hell_mirror: {
    playName: '孽镜照伪',
    toolName: '孽镜光',
    toolIcon: '🪞',
    fireLabel: '照破假面',
    hitVerb: '照中',
    criticalVerb: '原形暴照',
    finishMove: '假面破裂',
    dockHint: '别被表面温柔骗了，影子和假笑眼才是真弱点。',
    coreMechanic: '镜面会骗人，真正弱点藏在画皮影里。',
    rotationSpeed: 1.02,
    needleQuota: 10,
    weaknessParts: ['shadow', 'eyes'],
    obstacleType: 'mirror',
    specialRule: '假笑眼和影子才是破伪装入口。',
    recommendedWeapons: ['pin', 'stamp'],
    critMultiplier: 2.45,
    timeLimit: 85
  },
  hell_steam: {
    playName: '蒸笼封口',
    toolName: '热雾封符',
    toolIcon: '♨️',
    fireLabel: '封住话根',
    hitVerb: '封中',
    criticalVerb: '热雾暴封',
    finishMove: '恶气自蒸',
    dockHint: '热雾会挡视线，等嘴门和话根转到指针下再封。',
    coreMechanic: '热雾遮挡视线，抓住嘴门和话根的短窗口。',
    rotationSpeed: 1.16,
    needleQuota: 10,
    weaknessParts: ['mouth', 'throat'],
    obstacleType: 'fog',
    specialRule: '雾层会干扰判断，错扎会掉审判节奏。',
    recommendedWeapons: ['pin', 'glove'],
    critMultiplier: 2.3,
    timeLimit: 80
  },
  hell_copper: {
    playName: '铜柱锁贪',
    toolName: '铜链烙印',
    toolIcon: '⛓️',
    fireLabel: '锁回贪心',
    hitVerb: '锁中',
    criticalVerb: '贪心暴锁',
    finishMove: '借势反困',
    dockHint: '铜盾很厚，非弱点会被挡，先锁贪坑再锁黑心。',
    coreMechanic: '铜柱护甲厚，先破贪坑，再钉黑心。',
    rotationSpeed: 1.2,
    needleQuota: 12,
    weaknessParts: ['heart', 'belly'],
    obstacleType: 'shield',
    specialRule: '非弱点容易被护甲挡下，必须等贪坑和黑心转到指针下再锁。',
    recommendedWeapons: ['hammer', 'pin'],
    critMultiplier: 2.55,
    timeLimit: 80
  },
  hell_blade_mountain: {
    playName: '刀山断路',
    toolName: '刀山令',
    toolIcon: '🗡️',
    fireLabel: '斩断卡路',
    hitVerb: '斩中',
    criticalVerb: '设障暴斩',
    finishMove: '恶路自临',
    dockHint: '刀刃段会挡住攻击，抓脚和手，专砍它卡别人晋升的路。',
    coreMechanic: '刀山乱转，扎住卡路脚，别让小人继续设障。',
    rotationSpeed: 1.38,
    needleQuota: 12,
    weaknessParts: ['feet', 'hands'],
    obstacleType: 'blades',
    specialRule: '刀刃段会挡针，连续暴击能清空一截血条。',
    recommendedWeapons: ['glove', 'hammer'],
    critMultiplier: 2.6,
    timeLimit: 76
  },
  hell_ice: {
    playName: '冰山破冷',
    toolName: '冰封符',
    toolIcon: '❄️',
    fireLabel: '冻回冷暴力',
    hitVerb: '冻中',
    criticalVerb: '冷脸暴冻',
    finishMove: '自困冰山',
    dockHint: '冷暴力会拖慢节奏，冻住假笑眼和黑心，让冷气回到它身上。',
    coreMechanic: '冰山冷暴力会冻结节奏，钉住假笑眼和黑心。',
    rotationSpeed: 1,
    needleQuota: 12,
    weaknessParts: ['eyes', 'heart'],
    obstacleType: 'ice',
    specialRule: '命中弱点会解冻，错扎会让连击清零。',
    recommendedWeapons: ['pin', 'chime'],
    critMultiplier: 2.4,
    timeLimit: 80
  },
  hell_oil: {
    playName: '油锅反煎',
    toolName: '油锅判勺',
    toolIcon: '🫧',
    fireLabel: '煎回反咬',
    hitVerb: '煎中',
    criticalVerb: '反咬暴煎',
    finishMove: '因果自煎',
    dockHint: '泡泡是假目标，真正要煎的是反咬手和背刺点。',
    coreMechanic: '油锅泡泡会冒假目标，专钉反咬手和背刺点。',
    rotationSpeed: 1.48,
    needleQuota: 14,
    weaknessParts: ['hands', 'back'],
    obstacleType: 'bubbles',
    specialRule: '泡泡段只是话术浮沫，不要被诱导。',
    recommendedWeapons: ['glove', 'shredder'],
    critMultiplier: 2.65,
    timeLimit: 76
  },
  hell_ox: {
    playName: '牛坑套索',
    toolName: '牛马套索',
    toolIcon: '🪢',
    fireLabel: '套住吸血鬼',
    hitVerb: '套中',
    criticalVerb: '吸血暴套',
    finishMove: '自背其劳',
    dockHint: '它把人当牛马，就把贪坑和黑心套住，让消耗回流。',
    coreMechanic: '吸血牛马局会抽怒气，先扎贪坑和黑心。',
    rotationSpeed: 1.5,
    needleQuota: 14,
    weaknessParts: ['belly', 'heart'],
    obstacleType: 'drain',
    specialRule: '普通命中也有用，但暴击才能止住能量外流。',
    recommendedWeapons: ['hammer', 'glove'],
    critMultiplier: 2.7,
    timeLimit: 74
  },
  hell_stone: {
    playName: '石压回锅',
    toolName: '回锅石印',
    toolIcon: '🪨',
    fireLabel: '砸回甩锅',
    hitVerb: '压中',
    criticalVerb: '甩锅暴压',
    finishMove: '责任压身',
    dockHint: '锅段会压住攻击，命中甩锅脑和抢功手，锅就回本位。',
    coreMechanic: '甩锅从天上砸，钉住甩锅脑和抢功手。',
    rotationSpeed: 1.62,
    needleQuota: 14,
    weaknessParts: ['head', 'hands'],
    obstacleType: 'pots',
    specialRule: '锅段会压针，命中头部会触发锅回本位。',
    recommendedWeapons: ['hammer', 'stamp'],
    critMultiplier: 2.8,
    timeLimit: 72
  },
  hell_mortar: {
    playName: '舂臼捣乱',
    toolName: '返工舂杵',
    toolIcon: '⚒️',
    fireLabel: '捣碎返工',
    hitVerb: '捣中',
    criticalVerb: '折腾暴捣',
    finishMove: '混乱自碾',
    dockHint: '弱点会在头和心之间跳，别跟着它反复横跳。',
    coreMechanic: '返工折腾会变形，弱点在头和心之间跳。',
    rotationSpeed: 1.56,
    needleQuota: 16,
    weaknessParts: ['head', 'heart'],
    obstacleType: 'morphing',
    specialRule: '节奏会变快，别被反复横跳带走。',
    recommendedWeapons: ['glove', 'pin'],
    critMultiplier: 2.75,
    timeLimit: 70
  },
  hell_reputation: {
    playName: '血池洗污',
    toolName: '洗污血符',
    toolIcon: '🩸',
    fireLabel: '洗回污名',
    hitVerb: '洗中',
    criticalVerb: '污名暴洗',
    finishMove: '清白回流',
    dockHint: '污点会污染判断，嘴门、影子、黑心才是造谣源头。',
    coreMechanic: '污名脏点乱飞，扎住嘴门、影子和黑心。',
    rotationSpeed: 1.7,
    needleQuota: 16,
    weaknessParts: ['mouth', 'shadow', 'heart'],
    obstacleType: 'stains',
    specialRule: '污点段会污染审判值，暴击可洗回清白。',
    recommendedWeapons: ['pin', 'stamp'],
    critMultiplier: 2.85,
    timeLimit: 68
  },
  hell_wronged: {
    playName: '枉城判笔',
    toolName: '昭冤判笔',
    toolIcon: '🖌️',
    fireLabel: '判破假证',
    hitVerb: '判中',
    criticalVerb: '假证暴判',
    finishMove: '冤业昭明',
    dockHint: '假目标很多，判笔只打画皮影和甩锅脑。',
    coreMechanic: '假证目标很多，只有画皮影和甩锅脑是真的。',
    rotationSpeed: 1.78,
    needleQuota: 16,
    weaknessParts: ['shadow', 'head'],
    obstacleType: 'fakeTargets',
    specialRule: '假目标会给小人续命，必须认准弱点。',
    recommendedWeapons: ['stamp', 'hammer'],
    critMultiplier: 2.9,
    timeLimit: 66
  },
  hell_scheme: {
    playName: '磔刑拆局',
    toolName: '拆局钩',
    toolIcon: '🪝',
    fireLabel: '钩开恶局',
    hitVerb: '钩中',
    criticalVerb: '设局暴钩',
    finishMove: '恶局反锁',
    dockHint: '按背刺点、抢功手、黑心拆局，挖坑的人自己掉坑。',
    coreMechanic: '设局需要按顺序破：背刺点、抢功手、黑心。',
    rotationSpeed: 1.86,
    needleQuota: 18,
    weaknessParts: ['back', 'hands', 'heart'],
    obstacleType: 'sequence',
    specialRule: '连续命中弱点会把恶局反锁回去。',
    recommendedWeapons: ['pin', 'shredder'],
    critMultiplier: 3,
    timeLimit: 64
  },
  hell_volcano: {
    playName: '火山灭怒',
    toolName: '灭怒火符',
    toolIcon: '🌋',
    fireLabel: '反烧迁怒',
    hitVerb: '烧中',
    criticalVerb: '迁怒暴烧',
    finishMove: '怒火反噬',
    dockHint: '火口喷发会挡住窗口，等火势错开再反烧黑心和嘴门。',
    coreMechanic: '怒火喷发窗口很短，扎住黑心和嘴门反制迁怒。',
    rotationSpeed: 2,
    needleQuota: 18,
    weaknessParts: ['heart', 'mouth'],
    obstacleType: 'eruption',
    specialRule: '火山喷发段会挡针，等火口错开再发射。',
    recommendedWeapons: ['glove', 'chime'],
    critMultiplier: 3.05,
    timeLimit: 62
  },
  hell_millstone: {
    playName: '石磨归主',
    toolName: '归主磨盘',
    toolIcon: '⚙️',
    fireLabel: '磨回烂摊',
    hitVerb: '磨中',
    criticalVerb: '烂摊暴磨',
    finishMove: '烂摊归主',
    dockHint: '重甲很厚，盯住贪坑、脚和头，把烂摊子磨回它名下。',
    coreMechanic: '烂摊重甲拖着走，扎贪坑、脚和头。',
    rotationSpeed: 1.92,
    needleQuota: 20,
    weaknessParts: ['belly', 'feet', 'head'],
    obstacleType: 'heavyArmor',
    specialRule: '重甲会挡普通命中，优先抓住贪坑、脚和头的暴击窗口。',
    recommendedWeapons: ['hammer', 'shredder'],
    critMultiplier: 3.15,
    timeLimit: 60
  },
  hell_final: {
    playName: '阿鼻总判',
    toolName: '总账锯令',
    toolIcon: '⚔️',
    fireLabel: '执行总清算',
    hitVerb: '判中',
    criticalVerb: '无间暴判',
    finishMove: '十八层总账合卷',
    dockHint: '终局所有障碍上桌，认准嘴、影、心、背，把总账一次钉死。',
    coreMechanic: '十八层总账合并，所有障碍上桌，认准嘴、影、心、背。',
    rotationSpeed: 2.12,
    needleQuota: 24,
    weaknessParts: ['mouth', 'shadow', 'heart', 'back'],
    obstacleType: 'allCombined',
    specialRule: '终局层：错扎、撞针、挡针都会触发小人嘲讽。',
    recommendedWeapons: ['pin', 'hammer', 'chime'],
    critMultiplier: 3.4,
    timeLimit: 58
  }
};

export function getLevelMechanic(level: StressType): HellLevelMechanic {
  return LEVEL_MECHANICS[level.id] || LEVEL_MECHANICS.hell_tongue;
}
