[platformio]
default_envs = m5stickc

[env:m5stickc]
platform = espressif32@6.12.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.f_cpu = 160000000L
build_flags =
    -DCORE_DEBUG_LEVEL=1
lib_deps =
    m5stack/M5Unified @ 0.2.17
    m5stack/M5GFX @ 0.2.24

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<finish_work_logic.cpp> +<finish_work_model.cpp> +<button_classifier.cpp>
